### ISSUE TITLE
Issue with conversion_value_feature

### ISSUE THREAD

**Issue by ushkav17** [jmwoloso/pychattr#1]
Hi when I am fitting marcov model,  it shows 0 value in "markov value column": 
<img width="949" alt="zrzut ekranu 2018-08-12 o 17 14 04" src="https://user-images.githubusercontent.com/22856707/44003508-e8e477de-9e53-11e8-8f5b-9886d56a4542.png">

 and also have Warning :
`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:1472: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.
See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)
`

But when I debug code it start working:

<img width="954" alt="zrzut ekranu 2018-08-12 o 17 18 27" src="https://user-images.githubusercontent.com/22856707/44003510-ecab61a2-9e53-11e8-84d5-ab9b84f64c40.png">

I see that problem is in pychattr/channel_attribution.py file line:
517 - model = RChannelAttribution.markov_model(**kwargs)

I am using Python 3.7. Can you help me?

**Comment by jmwoloso** [comment]
@ushkav17 please post your code and a sample of your dataset. Additionally, post the versions you have installed for Cython, pandas, matplotlib and rpy2

**Comment by jmwoloso** [comment]
closing as we still need a code example. feel free to re-open.
