### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by DBa19** [jmwoloso/pychattr#2]
Hi,

I've tried getting this package to work and failed. Can you please let me know where I'm going wrong?
`from pychattr import channel_attribution

model = channel_attribution.PyChAttr(df=df markov_model=True, path_feature='final_channel', conversion_feature='conversion')
`
The returned model is not a dataframe, but:
 <pychattr.channel_attribution.PyChAttr at 0x186ccd43a58>

P.S.
I've tried to port the channel attribution package from R by myself with rpy2, and while it's working, it is returning the wrong results for the data selected and not sure why. I have a feeling it's related to the data types transformed by pandas. Did you encounter this issue by any chance?

Thanks

**Comment by jmwoloso** [comment]
Hi @DBa19! Sorry for getting back so late. I'm in the process of re-vamping the library to eliminate the need for R completely and in doing so, I've refactored and removed the PyChAttr class in favor of splitting the models out into the heuristic and markov components separately.

Follow releases on the repo so you're automatically notified when new releases happen and/or I can ping you when the new version is available.

**Comment by jmwoloso** [comment]
@DBa19 I removed my dev code for additional features I was working on and released v0.2.0. Try it out now and see if you have any issues.
